"""add source_document_id to templates

Revision ID: 491fa0d17bea
Revises: b1c2d3e4f5a6
Create Date: 2026-04-02 22:03:49.418881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491fa0d17bea'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('source_document_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_templates_source_document_id'), 'templates', ['source_document_id'], unique=False)
    op.create_foreign_key(None, 'templates', 'documents', ['source_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_index(op.f('ix_templates_source_document_id'), table_name='templates')
    op.drop_column('templates', 'source_document_id')
    # ### end Alembic commands ###
