"""add terms_agreed field to users

Revision ID: 93fe2378a198
Revises: d01a52abb27b
Create Date: 2026-03-28 14:51:43.253812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fe2378a198'
down_revision: Union[str, Sequence[str], None] = 'd01a52abb27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_agreed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_terms_agreed'), 'users', ['terms_agreed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_terms_agreed'), table_name='users')
    op.drop_column('users', 'terms_agreed')
    # ### end Alembic commands ###
